/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-12-12 16:37:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.ForEach;
import Dominio.*;
import Dominio.Provincia;
import DAO.*;
import java.util.ArrayList;

public final class alumnos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("DAO");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Dominio");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.ForEach");
    _jspx_imports_classes.add("Dominio.Provincia");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Sistema Universitarios</title>\r\n");
      out.write("<link href=\"estilos.css\" type=\"text/css\" rel=stylesheet>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Oswald&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Francois+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"jquery.dataTables.min.css\" type=\"text/css\" rel=sytlesheet>\r\n");
      out.write("<script src=\"jquery-3.4.1.min.js\"></script>\r\n");
      out.write(" <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"jquery.dataTables.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 /*
	if((Usuario) request.getSession(true).getAttribute("usuario")!=null){
		
		Usuario unUsuario = new Usuario();
		unUsuario = (Usuario) request.getSession(true).getAttribute("usuario");
		if(!unUsuario.getTipoUsuario().equals("administrador")){response.sendRedirect("error404.jsp");}
	
	}

	else {
		response.sendRedirect("error404.jsp");
	}*/
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<nav>\r\n");
      out.write("<div id=\"user\">\r\n");
      out.write("\t\t<a href=\"index.jsp\"><img id=\"icon-usuario\" src=\"iconos/usuario-admin.svg\" alt=\"imagen-usuario\"></a>\r\n");
      out.write("\t\t<h2>¡Bienvenido!</h2>\r\n");
      out.write("\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t<a href=\"serveletUsuario\">LogOut</a>\r\n");
      out.write("\t</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu-administrador.html", out, false);
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<section class=\"section-principal\">\r\n");
      out.write("\t<div class=\"encabezados\"><h3>LISTADO DE ALUMNOS</h3></div>\r\n");
      out.write("\t<div id=\"form-listado-alumnos\">\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"btnAgregar\" class=\"btnFormulario\" value=\"AGREGAR ALUMNO\">\t\t\r\n");
      out.write("\t\t\t<!---------------------------------------------------------------------------------------------------------------\r\n");
      out.write("\t\t\t\t\tTABLA - LISTADO ALUMNOS\r\n");
      out.write("\t\t\t<!-------------------------------------------------------------------------------------------------------------->\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table id=\"table_id\" class=\"content-table\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Legajo</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Nombre</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Apellido</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Fecha de Nacimiento</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Dirección</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Localidad</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Provincia</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Email</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Teléfono</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Opciones</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 
			AlumnosDAO unAlumnoDAO = new AlumnosDAO(); 
			for(Alumno unAlumno : unAlumnoDAO.ListadoAlumnos()){
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>  \r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unAlumno.getLegajo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unAlumno.getNombre() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unAlumno.getApellido() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unAlumno.getFechaNacimiento() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unAlumno.getDireccion() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unAlumno.getLocalidad() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unAlumno.getLocalidad().getProvincia() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unAlumno.getEmail() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unAlumno.getTelefono() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t  <td>\r\n");
      out.write("\t\t\t\t\t\t  \t  <input type=\"button\" class=\"btn-modificar\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t  \t  <input type=\"button\" class=\"btn-eliminar\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t  ");
}
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<!---------------------------------------------------------------------------------------------------------------\r\n");
      out.write("\t\t\t\t\tFORMULARIO EMERGENTE - AGREGAR/MODIFICAR ALUMNOS\r\n");
      out.write("\t\t\t<!-------------------------------------------------------------------------------------------------------------->\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-fondo\" id=\"modal-fondo\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-contenido\" id=\"modal-contenido\">\r\n");
      out.write("\t\t\t\t\t<h3>DATOS ALUMNO</h3><br>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"ServeletAlumno\" id=\"form-datos\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"tipoFormulario\" name=\"tipoFormulario\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t<label>Legajo<br><input type=\"text\" id=\"tboxLegajo\" name=\"tboxLegajo\" readonly=\"true\" required></label><br>\r\n");
      out.write("\t\t\t\t\t\t<label>Nombre<br><input type=\"text\" id=\"tboxNombre\" name=\"tboxNombre\" required  ></label><br>\r\n");
      out.write("\t\t\t\t\t\t<label>Apellido<br><input type=\"text\" id=\"tboxApellido\" name=\"tboxApellido\" required></label><br>\r\n");
      out.write("\t\t\t\t\t\t<label>Fecha de Nacimiento</label><br><input type=\"date\" id=\"tboxFechaNacimiento\" name=\"tboxFechaNacimiento\" required><br>\r\n");
      out.write("\t\t\t\t\t\t<label>Direccion<br><input type=\"text\" id=\"tboxDireccion\" name=\"tboxDireccion\" required></label><br>\r\n");
      out.write("\t\t\t\t\t\t<label>Provincias</label><br>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"cboxProvincias\" id=\"cboxProvincias\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<option disabled selected>Seleccione una provincia</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							ProvinciasDAO Provincias = new ProvinciasDAO();
							for(Provincia unaProvincia : Provincias.ListadoProvincias()){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option class=\"opciones\" value=\"");
      out.print(unaProvincia.getIdProvincia());
      out.write('"');
      out.write('>');
      out.print( unaProvincia.getNombre());
      out.write("</option>");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select><br>\r\n");
      out.write("\t\t\t\t\t\t<label>Localidades</label><br>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"cboxLocalidades\" id=\"cboxLocalidades\" required></select>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<label>E-mail<br><input type=\"email\" id=\"tboxEmail\" name=\"tboxEmail\" required></label><br>\r\n");
      out.write("\t\t\t\t\t\t<label>Teléfono<br><input type=\"number\" id=\"tboxTelefono\" name=\"tboxTelefono\" required></label><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"btn-modal\" id=\"btnAceptar\" name=\"btnAceptar\" value=\"Aceptar\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn-modal\" id=\"btnCerrar\" value=\"Cancelar\">\t\t\r\n");
      out.write("\t\t\t\t\t</form>\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!---------------------------------------------------------------------------------------------------------------\r\n");
      out.write("\t\t\t\t\tFORMULARIO EMERGENTE - BORRAR ALUMNO\r\n");
      out.write("\t\t\t<!-------------------------------------------------------------------------------------------------------------->\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal-fondo\" id=\"modal-fondo-advertencia\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-contenido\" id=\"modal-advertencia\">\r\n");
      out.write("\t\t\t\t\t\t<h3>ELIMINAR REGISTRO</h3><br>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t <a href=\"#\" id=\"eliminar-alumno\">Borrar</a>\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"button\" class=\"btn-modal\" id=\"btnCancelar\" value=\"Cancelar\">\t\r\n");
      out.write("\t\t\t\t\t\t  <p>¿Está seguro que desea eliminar el legajo<label id=\"registroEliminar\" name=\"registroEliminar\"></label> ?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"funciones.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t$(\"td\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#tboxLegajo').val($(this).parents(\"tr\").find(\"td\").eq(0).text());\r\n");
      out.write("\t\t\t$('#tboxNombre').val($(this).parents(\"tr\").find(\"td\").eq(1).text());\r\n");
      out.write("\t\t\t$('#tboxApellido').val($(this).parents(\"tr\").find(\"td\").eq(2).text());\t\t\t\r\n");
      out.write("\t\t\t$('#tboxFechaNacimiento').val($(this).parents(\"tr\").find(\"td\").eq(3).text());\r\n");
      out.write("\t\t\t$('#tboxDireccion').val($(this).parents(\"tr\").find(\"td\").eq(4).text());\r\n");
      out.write("\t\t\t$('#tboxEmail').val($(this).parents(\"tr\").find(\"td\").eq(7).text());\r\n");
      out.write("\t\t\t$('#tboxTelefono').val($(this).parents(\"tr\").find(\"td\").eq(8).text());\r\n");
      out.write("\t\t\tvar registroEliminar =$(this).parents(\"tr\").find(\"td\").eq(0).text();\r\n");
      out.write("\t\t\tvar link = \"ServeletAlumno?EliminarAlumno=\"+registroEliminar;\r\n");
      out.write("\t\t\t$(\"#registroEliminar\").text(registroEliminar);\r\n");
      out.write("\t\t\t$(\"#eliminar-alumno\").attr(\"href\", link);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(document.getElementById(\"tipoFormulario\").value === 'modificar'){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconst provinciaSeleccionada = $(this).parents(\"tr\").find(\"td\").eq(6).text();\r\n");
      out.write("\t\t\t\tconst localidadSeleccionada = $(this).parents(\"tr\").find(\"td\").eq(5).text();\r\n");
      out.write("\t\t\t\tconst indexProvinciaSeleccionada = document.getElementById(\"cboxProvincias\").value;\r\n");
      out.write("\t\t\t\tconst desplegableLocalidad = document.getElementById(\"cboxLocalidades\");\r\n");
      out.write("\t\t\t\tconst desplegableProvincias = document.getElementById(\"cboxProvincias\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i=1;i<desplegableProvincias.length;i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(desplegableProvincias.options[i].text==provinciaSeleccionada) desplegableProvincias.selectedIndex=i;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t $('#cboxLocalidades option').remove();\t\t\t\r\n");
      out.write("\t\t\t\t ");

				 LocalidadesDAO Localidad = new LocalidadesDAO();
							 
				 for(Localidad unaLocalidad : Localidad.ListadoLocalidades()){
      out.write("\t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t \tif(desplegableProvincias.selectedIndex===");
      out.print(unaLocalidad.getProvincia().getIdProvincia());
      out.write("){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar item = document.createElement('option');\r\n");
      out.write("\t\t\t\t\t\titem.value = '");
      out.print(unaLocalidad.getIdLocalidad());
      out.write("';\r\n");
      out.write("\t\t\t\t\t\titem.innerHTML = '");
      out.print(unaLocalidad.getNombre());
      out.write("';\r\n");
      out.write("\t\t\t\t\t\tdesplegableLocalidad.appendChild(item);\r\n");
      out.write("\t\t\t\t\t }\t\t\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i=1;i<desplegableLocalidad.length;i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(desplegableLocalidad.options[i].text==localidadSeleccionada) desplegableLocalidad.selectedIndex=i;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t$('#cboxProvincias').change(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#cboxLocalidades option').remove();\r\n");
      out.write("\t\t\tLocalidadSeleccionada(this,'cboxLocalidades');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction LocalidadSeleccionada(cboxProvincias, cboxLocalidades){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconst provinciaSeleccionada = document.getElementById(\"cboxProvincias\").value;\r\n");
      out.write("\t\t\t\tconst desplegableLocalidad = document.getElementById(\"cboxLocalidades\");\r\n");
      out.write("\t\t\t        \t\t\r\n");
      out.write("\t\t\t\t ");

				 for(Localidad unaLocalidad : Localidad.ListadoLocalidades()){
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t if(provinciaSeleccionada==");
      out.print(unaLocalidad.getProvincia().getIdProvincia());
      out.write("){\r\n");
      out.write("\t\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t\tvar item = document.createElement('option');\r\n");
      out.write("\t\t\t\t\t\titem.value = '");
      out.print(unaLocalidad.getIdLocalidad());
      out.write("';\r\n");
      out.write("\t\t\t\t\t\titem.innerHTML = '");
      out.print(unaLocalidad.getNombre());
      out.write("';\r\n");
      out.write("\t\t\t\t\t\tdesplegableLocalidad.appendChild(item);\r\n");
      out.write("\t\t\t\t\t }\t\t\r\n");
      out.write("\t\t\t\t");
}
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
