/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-20 00:26:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Dominio.Curso;
import Dominio.Alumno;
import java.util.ArrayList;

public final class cursosporprofesor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Dominio.Alumno");
    _jspx_imports_classes.add("Dominio.Curso");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Sistema Universitarios</title>\r\n");
      out.write("<link href=\"estilos.css\" type=\"text/css\" rel=stylesheet>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Oswald&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Francois+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"jquery.dataTables.min.css\" type=\"text/css\" rel=sytlesheet>\r\n");
      out.write("<script src=\"jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"jquery.dataTables.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu-profesores.html", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"section-principal\">\r\n");
      out.write("\t<div class=\"encabezados\"><h3>CURSOS ASOCIADOS</h3></div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"form-listado-calificaciones\">\r\n");
      out.write("\t\t\t<h2>LISTADO DE CURSOS</h2>\r\n");
      out.write("\t\t\t<table id=\"table_id\" class=\"content-table\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Código Curso</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Materia</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Semestre</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Año</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Alumnos</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t");
 
		
				
			for(Curso unCurso : Curso.CargarCurso()){ 
			
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>  \r\n");
      out.write("\t\t\t\t\t\t  <td>");
      out.print( unCurso.getIdCurso() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t    <td>");
      out.print( unCurso.getMateria().getNombre() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t    <td>");
      out.print( unCurso.getSemestre() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t    <td>");
      out.print( unCurso.getAnio() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t            <td>\r\n");
      out.write("\t\t\t\t            <a href=\"calificaciones.jsp\"><input type=\"button\" class=\"btn-mostrar\" value=\"\"></a>\r\n");
      out.write("\t\t\t\t            <a href=\"calificaciones.jsp\"><input type=\"button\" class=\"btn-calificaciones\" value=\"\"></a>\r\n");
      out.write("\t\t\t\t            </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t  ");
	
				}
				
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"modal-fondo\" id=\"modal-fondo-advertencia\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal-contenido\" id=\"modal-advertencia\">\r\n");
      out.write("\t\t\t\t\t<h3>ELIMINAR REGISTRO</h3><br>\r\n");
      out.write("\t\t\t\t\t <p>¿Está seguro que desea eliminar el legajo<label id=\"registroEliminar\"></label>?</p>\r\n");
      out.write("\t\t\t\t\t <input type=\"button\" class=\"btn-modal\" id=\"btnBorrar\" value=\"Borrar\">\r\n");
      out.write("\t\t\t\t\t <input type=\"button\" class=\"btn-modal\" id=\"btnCancelar\" value=\"Cancelar\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t/*const flecha = document.getElementById('btn-flecha').addEventListener('click',mostarDiv);\r\n");
      out.write("\t\r\n");
      out.write("\tfunction mostarDiv(){\r\n");
      out.write("\t\r\n");
      out.write("\t    document.getElementById('form-agregar-usuario').style.display = 'block';\r\n");
      out.write("\t\r\n");
      out.write("\t}*/\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready( function () {\r\n");
      out.write("\t    $('#table_id').DataTable();\r\n");
      out.write("\t} );\r\n");
      out.write("\t\r\n");
      out.write("\tconst btnAbrir = document.getElementById('btnAgregarAlumno');\r\n");
      out.write("\tvar btnEliminar = document.getElementsByClassName('btn-eliminar');\r\n");
      out.write("\tvar btnModificar = document.getElementsByClassName('btn-modificar');\r\n");
      out.write("\tconst fondo = document.getElementById('modal-fondo');\r\n");
      out.write("\tconst ventanaEmergente = document.getElementById('modal-contenido');\r\n");
      out.write("\tconst ventanaAdvertencia = document.getElementById('modal-advertencia');\r\n");
      out.write("\tconst fondoAdvertencia = document.getElementById('modal-fondo-advertencia');\r\n");
      out.write("\tconst btnCerrar = document.getElementById('btnCerrar');\r\n");
      out.write("\tconst btnCerrarAdvertencia = document.getElementById('btnCancelar');btnCancelar\r\n");
      out.write("\t\r\n");
      out.write("\tbtnAbrir.addEventListener('click', function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfondo.classList.add('active');\r\n");
      out.write("\t\tdocument.getElementById('form-datos-alumnos').reset();\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfor (var i=0; i< btnModificar.length; i++) {\r\n");
      out.write("        \r\n");
      out.write("        btnModificar[i].addEventListener(\"click\",function() {\r\n");
      out.write("        \t\r\n");
      out.write("        \tfondo.classList.add('active');\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\tfor (var i=0; i< btnEliminar.length; i++) {\r\n");
      out.write("        \r\n");
      out.write("\t\tbtnEliminar[i].addEventListener(\"click\",function() {\r\n");
      out.write("        \t\r\n");
      out.write("        \tfondoAdvertencia.classList.add('active');\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\tbtnCerrar.addEventListener('click', function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfondo.classList.remove('active');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tbtnCerrarAdvertencia.addEventListener('click', function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfondoAdvertencia.classList.remove('active');\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t$(\"td\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#tboxLegajo').val($(this).parents(\"tr\").find(\"td\").eq(0).text());\r\n");
      out.write("\t\t\t$('#tboxNombre').val($(this).parents(\"tr\").find(\"td\").eq(1).text());\r\n");
      out.write("\t\t\t$('#tboxApellido').val($(this).parents(\"tr\").find(\"td\").eq(2).text());\r\n");
      out.write("\t\t\t$('#tboxFechaNacimiento').val($(this).parents(\"tr\").find(\"td\").eq(3).text());\r\n");
      out.write("\t\t\t$('#tboxLocalidad').val($(this).parents(\"tr\").find(\"td\").eq(4).text());\r\n");
      out.write("\t\t\t$('#tboxProvincia').val($(this).parents(\"tr\").find(\"td\").eq(5).text());\r\n");
      out.write("\t\t\t$('#tboxEmail').val($(this).parents(\"tr\").find(\"td\").eq(6).text());\r\n");
      out.write("\t\t\t$('#tboxTelefono').val($(this).parents(\"tr\").find(\"td\").eq(7).text());\r\n");
      out.write("\t\t\t$(\"#registroEliminar\").text($(this).parents(\"tr\").find(\"td\").eq(0).text());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
